# Generated by Django 6.0.3 on 2026-04-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listado_productos_supli',
            fields=[
                ('UPC', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('marca_producto', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'listado_productos_supli',
                'ordering': ['nombre_producto'],
            },
        ),
    ]
