# Generated by Django 6.0.3 on 2026-04-08 20:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listado_productos_internacionales',
            fields=[
                ('upc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha_lista', models.DateField()),
                ('nombre', models.CharField(max_length=200)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_disponible', models.IntegerField()),
                ('proveedores', models.CharField(max_length=200)),
                ('factor_logistico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('costo_con_factor_logistico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
            ],
            options={
                'db_table': 'listado_productos_internacionales',
                'ordering': ['nombre'],
            },
        ),
    ]
