# Generated by Django 6.0.3 on 2026-04-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_compras', '0003_listado_productos_nacionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado_productos_internacionales',
            name='upc',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='listado_productos_nacionales',
            name='upc',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='listado_productos_internacionales',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='listado_productos_nacionales',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
