# Generated by Django 6.0.3 on 2026-04-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_compras', '0004_listado_productos_internacionales_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listado_productos_internacionales',
            name='upc',
            field=models.CharField(max_length=50),
        ),
    ]
