from django.urls import path

from . import views

app_name = "abastecimientos"

urlpatterns = [
    path("canales/", views.canal_list, name="canal_list"),
    path("canales/crear/", views.canal_create, name="canal_create"),
    path("canales/<str:pk>/editar/", views.canal_update, name="canal_update"),
    path("canales/<str:pk>/eliminar/", views.canal_delete, name="canal_delete"),
    path("canales/exportar/", views.canal_export, name="canal_export"),
    path("canales/importar/", views.canal_import, name="canal_import"),
    path("productos/", views.producto_list, name="producto_list"),
    path("productos/crear/", views.producto_create, name="producto_create"),
    path("productos/<str:pk>/editar/", views.producto_update, name="producto_update"),
    path("productos/<str:pk>/eliminar/", views.producto_delete, name="producto_delete"),
    path("productos/exportar/", views.producto_export, name="producto_export"),
    path("productos/importar/", views.producto_import, name="producto_import"),
    path("productos/eliminar-por-canal/", views.producto_delete_by_canal, name="producto_delete_by_canal"),
    path("puntos-venta/", views.punto_venta_list, name="punto_venta_list"),
    path("puntos-venta/crear/", views.punto_venta_create, name="punto_venta_create"),
    path("puntos-venta/<str:pk>/editar/", views.punto_venta_update, name="punto_venta_update"),
    path("puntos-venta/<str:pk>/eliminar/", views.punto_venta_delete, name="punto_venta_delete"),
    path("puntos-venta/exportar/", views.punto_venta_export, name="punto_venta_export"),
    path("puntos-venta/importar/", views.punto_venta_import, name="punto_venta_import"),
    path("puntos-venta/eliminar-por-canal/", views.punto_venta_delete_by_canal, name="punto_venta_delete_by_canal"),
    path("inventarios/", views.inventario_list, name="inventario_list"),
    path("inventarios/crear/", views.inventario_create, name="inventario_create"),
    path("inventarios/<int:pk>/editar/", views.inventario_update, name="inventario_update"),
    path("inventarios/<int:pk>/eliminar/", views.inventario_delete, name="inventario_delete"),
    path("inventarios/exportar/", views.inventario_export, name="inventario_export"),
    path("inventarios/importar/", views.inventario_import, name="inventario_import"),
    path("inventarios/eliminar-por-canal/", views.inventario_delete_by_canal, name="inventario_delete_by_canal"),
    path("metas/", views.meta_list, name="meta_list"),
    path("metas/crear/", views.meta_create, name="meta_create"),
    path("metas/<int:pk>/editar/", views.meta_update, name="meta_update"),
    path("metas/<int:pk>/eliminar/", views.meta_delete, name="meta_delete"),
    path("metas/exportar/", views.meta_export, name="meta_export"),
    path("metas/importar/", views.meta_import, name="meta_import"),
    path("metas/eliminar-por-canal/", views.meta_delete_by_canal, name="meta_delete_by_canal"),
    path("transitos/", views.transito_list, name="transito_list"),
    path("transitos/crear/", views.transito_create, name="transito_create"),
    path("transitos/<int:pk>/editar/", views.transito_update, name="transito_update"),
    path("transitos/<int:pk>/eliminar/", views.transito_delete, name="transito_delete"),
    path("transitos/exportar/", views.transito_export, name="transito_export"),
    path("transitos/importar/", views.transito_import, name="transito_import"),
    path("transitos/eliminar-por-canal/", views.transito_delete_by_canal, name="transito_delete_by_canal"),
    path("ventas/", views.venta_list, name="venta_list"),
    path("ventas/crear/", views.venta_create, name="venta_create"),
    path("ventas/<int:pk>/editar/", views.venta_update, name="venta_update"),
    path("ventas/<int:pk>/eliminar/", views.venta_delete, name="venta_delete"),
    path("ventas/exportar/", views.venta_export, name="venta_export"),
    path("ventas/importar/", views.venta_import, name="venta_import"),
    path("ventas/eliminar-por-canal/", views.venta_delete_by_canal, name="venta_delete_by_canal"),
    path("abastecimiento-claro/", views.abastecimiento_claro_list, name="abastecimiento_claro_list"),
    path("abastecimiento-claro/crear/", views.abastecimiento_claro_create, name="abastecimiento_claro_create"),
    path("abastecimiento-claro/<uuid:pk>/editar/", views.abastecimiento_claro_update, name="abastecimiento_claro_update"),
    path("abastecimiento-claro/<uuid:pk>/eliminar/", views.abastecimiento_claro_delete, name="abastecimiento_claro_delete"),
    path("abastecimiento-claro/exportar/", views.abastecimiento_claro_export, name="abastecimiento_claro_export"),
    path("abastecimiento-claro/importar/", views.abastecimiento_claro_import, name="abastecimiento_claro_import"),
    path("abastecimiento-coltrade/", views.abastecimiento_coltrade_list, name="abastecimiento_coltrade_list"),
    path("abastecimiento-coltrade/crear/", views.abastecimiento_coltrade_create, name="abastecimiento_coltrade_create"),
    path("abastecimiento-coltrade/<uuid:pk>/editar/", views.abastecimiento_coltrade_update, name="abastecimiento_coltrade_update"),
    path("abastecimiento-coltrade/<uuid:pk>/eliminar/", views.abastecimiento_coltrade_delete, name="abastecimiento_coltrade_delete"),
    path("abastecimiento-coltrade/exportar/", views.abastecimiento_coltrade_export, name="abastecimiento_coltrade_export"),
    path("abastecimiento-coltrade/importar/", views.abastecimiento_coltrade_import, name="abastecimiento_coltrade_import"),
    path("unir/", views.unir_archivos_page, name="unir_archivos_page"),
    path("unir/preview/", views.unir_archivos_preview, name="unir_archivos_preview"),
    path("unir/merge/", views.unir_archivos_merge, name="unir_archivos_merge"),
    path("forecast/", views.forecast_page, name="forecast_page"),
    path("forecast/options/", views.forecast_options, name="forecast_options"),
    path("forecast/data/", views.forecast_data, name="forecast_data"),
    path("cruzar-archivos/", views.cruzar_archivos_page, name="cruzar_archivos"),
    path(
        "cruzar-archivos/data/",
        views.cruzar_archivos_data,
        name="cruzar_archivos_data",
    ),
    path(
        "cruzar-archivos/export/",
        views.cruzar_archivos_export,
        name="cruzar_archivos_export",
    ),
    path("serializar-ventas/", views.serializar_ventas_page, name="serializar_ventas"),
    path(
        "serializar-ventas/preview/",
        views.serializar_ventas_preview,
        name="serializar_ventas_preview",
    ),
    path(
        "serializar-ventas/process/",
        views.serializar_ventas_process,
        name="serializar_ventas_process",
    ),
    path(
        "home_abastecimiento/",
        views.home_abastecimiento,
        name="home_abastecimiento",
    ),


    
]

