# Generated by Django 6.0.3 on 2026-08-13 16:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('puntaje_max', models.PositiveSmallIntegerField(default=25)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pulse_pilares',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CicloPulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('activo', 'Activo'), ('cerrado', 'Cerrado'), ('publicado', 'Publicado')], default='programado', max_length=20)),
                ('puntaje_max', models.PositiveSmallIntegerField(default=100)),
                ('ranking_publicado', models.BooleanField(default=False, help_text='Si esta activo, el ranking es visible para todos los lideres')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pulse_ciclos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pulse_ciclos',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='MiembroLeadershipTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_membresia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pulse_miembros',
                'ordering': ['usuario__nombre', 'usuario__apellido'],
            },
        ),
        migrations.CreateModel(
            name='RetoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveSmallIntegerField(choices=[(1, 'Semana 1'), (2, 'Semana 2'), (3, 'Semana 3'), (4, 'Semana 4')])),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('criterio_cumplimiento', models.TextField(blank=True, help_text='Que se considera cumplir el reto (10 pts)')),
                ('criterio_evidencia', models.TextField(blank=True, help_text='Que evidencia objetiva se debe presentar (5 pts)')),
                ('criterio_impacto', models.TextField(blank=True, help_text='Que se considera impacto demostrable (10 pts)')),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('puntaje_max', models.PositiveSmallIntegerField(default=25)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retos', to='leadership_pulse.ciclopulse')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retos', to='leadership_pulse.pilar')),
            ],
            options={
                'db_table': 'pulse_retos',
                'ordering': ['ciclo', 'semana'],
                'unique_together': {('ciclo', 'semana')},
            },
        ),
        migrations.CreateModel(
            name='PuntajeMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.PositiveSmallIntegerField(default=0)),
                ('detalle_pilares', models.JSONField(blank=True, default=dict, help_text="{codigo_pilar: {'nombre':..., 'puntaje':..., 'max':...}}")),
                ('retos_evaluados', models.PositiveSmallIntegerField(default=0)),
                ('retos_cumplidos', models.PositiveSmallIntegerField(default=0)),
                ('semaforo', models.CharField(choices=[('champion', 'Leadership Champion'), ('alto', 'Alto desempeno'), ('consolidacion', 'En consolidacion'), ('fortalecimiento', 'Requiere fortalecimiento'), ('intervencion', 'Requiere intervencion')], default='intervencion', max_length=20)),
                ('posicion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='leadership_pulse.ciclopulse')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_puntajes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pulse_puntajes_mensuales',
                'ordering': ['-puntaje_total', 'lider__nombre'],
                'unique_together': {('ciclo', 'lider')},
            },
        ),
        migrations.CreateModel(
            name='ParticipacionReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revision'), ('validado', 'Validado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20)),
                ('declara_cumplimiento', models.BooleanField(default=False)),
                ('evidencia_url', models.URLField(blank=True)),
                ('evidencia_descripcion', models.TextField(blank=True)),
                ('impacto_descripcion', models.TextField(blank=True)),
                ('pts_cumplimiento', models.PositiveSmallIntegerField(default=0)),
                ('pts_evidencia', models.PositiveSmallIntegerField(default=0)),
                ('pts_impacto', models.PositiveSmallIntegerField(default=0)),
                ('puntaje_total', models.PositiveSmallIntegerField(default=0)),
                ('observaciones_validador', models.TextField(blank=True)),
                ('fecha_reporte', models.DateTimeField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_participaciones', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pulse_validaciones', to=settings.AUTH_USER_MODEL)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='leadership_pulse.retosemanal')),
            ],
            options={
                'db_table': 'pulse_participaciones',
                'ordering': ['reto__semana', 'lider__nombre'],
                'unique_together': {('reto', 'lider')},
            },
        ),
    ]
