# Generated by Django 6.0.3 on 2026-08-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership_pulse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puntajemensual',
            options={'ordering': ['-pct_cumplimiento', '-pct_participacion', 'lider__nombre']},
        ),
        migrations.AddField(
            model_name='participacionreto',
            name='cumplio',
            field=models.BooleanField(default=False, help_text='La persona cumplio el reto asignado'),
        ),
        migrations.AddField(
            model_name='participacionreto',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Seguimiento del reto: contexto, soportes o acuerdos'),
        ),
        migrations.AddField(
            model_name='participacionreto',
            name='participo',
            field=models.BooleanField(default=False, help_text='La persona participo en el reto asignado'),
        ),
        migrations.AddField(
            model_name='puntajemensual',
            name='pct_cumplimiento',
            field=models.FloatField(default=0, help_text='Cumplidos / asignados (%)'),
        ),
        migrations.AddField(
            model_name='puntajemensual',
            name='pct_participacion',
            field=models.FloatField(default=0, help_text='Participados / asignados (%)'),
        ),
        migrations.AddField(
            model_name='puntajemensual',
            name='retos_participados',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='puntajemensual',
            name='retos_registrados',
            field=models.PositiveSmallIntegerField(default=0, help_text='Retos con registro de seguimiento'),
        ),
        migrations.AlterField(
            model_name='participacionreto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Sin registrar'), ('en_revision', 'Reportado por el lider'), ('validado', 'Registrado'), ('devuelto', 'Devuelto al lider')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='puntajemensual',
            name='retos_evaluados',
            field=models.PositiveSmallIntegerField(default=0, help_text='Retos asignados en el ciclo'),
        ),
    ]
