# Generated by Django 6.0.3 on 2026-03-26 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id_asesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
                'db_table': 'asesor',
            },
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id_coordinador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Coordinador',
                'verbose_name_plural': 'Coordinadores',
                'db_table': 'coordinador',
            },
        ),
        migrations.CreateModel(
            name='PuntoVentaMalla',
            fields=[
                ('id_punto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=50)),
                ('asesor_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_default_asesor', to='malla_operaciones_trade.asesor')),
                ('coordinador_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_default_coordinador', to='malla_operaciones_trade.coordinador')),
            ],
            options={
                'verbose_name': 'Punto de Venta Malla',
                'verbose_name_plural': 'Puntos de Venta Malla',
                'db_table': 'punto_venta_malla',
            },
        ),
        migrations.CreateModel(
            name='RegistroLaboral',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VACANTE', 'Vacante'), ('INCAPACIDAD', 'Incapacidad'), ('DESCANSO', 'Descanso')], max_length=20)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('horas_trabajadas', models.FloatField(default=0)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='malla_operaciones_trade.asesor')),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='malla_operaciones_trade.coordinador')),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malla_operaciones_trade.puntoventamalla')),
            ],
            options={
                'verbose_name': 'Registro Laboral',
                'verbose_name_plural': 'Registros Laborales',
                'db_table': 'registro_laboral',
            },
        ),
    ]
