# Generated by Django 6.0.3 on 2026-03-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malla_operaciones_trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoventamalla',
            name='zona',
            field=models.CharField(choices=[('Zona Sur', 'Zona Sur'), ('Zona Norte', 'Zona Norte')], max_length=50),
        ),
    ]
