# Generated by Django 6.0.3 on 2026-03-31 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionPPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('estrategico', 'Estrategico'), ('tactico', 'Tactico'), ('desarrollo', 'Desarrollo'), ('activacion_bienestar', 'Activacion & Bienestar')], max_length=30)),
                ('puntos_min', models.PositiveIntegerField()),
                ('puntos_max', models.PositiveIntegerField()),
                ('puntos_default', models.PositiveIntegerField()),
                ('solo_lideres', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pps_acciones',
                'ordering': ['nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('reconocimiento', 'Reconocimiento'), ('tiempo', 'Tiempo Flexible'), ('certificado', 'Certificado / Medalla Digital'), ('sorteo', 'Sorteo / Experiencia'), ('desarrollo', 'Desarrollo')], max_length=30)),
                ('puntos_requeridos', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Dejar vacio si es ilimitado', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pps_beneficios',
                'ordering': ['puntos_requeridos'],
            },
        ),
        migrations.CreateModel(
            name='PuntosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales', models.IntegerField(default=0)),
                ('nivel', models.CharField(choices=[('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro'), ('diamante', 'Diamante')], default='bronce', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_pps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pps_puntos_usuario',
            },
        ),
        migrations.CreateModel(
            name='ReclamoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reclamo', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('puntos_descontados', models.PositiveIntegerField()),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamos', to='bienestar_coltrade.beneficio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos_pps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pps_reclamos_beneficios',
                'ordering': ['-fecha_reclamo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_evidencia', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('puntos_asignados', models.IntegerField(default=0)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observacion_lider', models.TextField(blank=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='bienestar_coltrade.accionpps')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_pps', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pps_registro_acciones',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
