# Generated by Django 6.0.3 on 2026-04-06 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar_coltrade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accionpps',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accionpps',
            name='nivel',
            field=models.CharField(choices=[('estrategico', 'Estrategico'), ('tactico', 'Tactico'), ('desarrollo', 'Desarrollo'), ('activacion_bienestar', 'Activacion & Bienestar'), ('capacitacion', 'Capacitacion')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProgresoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso_pct', models.PositiveSmallIntegerField(default=0)),
                ('puntos_otorgados', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones_progreso', to='bienestar_coltrade.accionpps')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones_pps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pps_capacitaciones_progreso',
                'unique_together': {('usuario', 'accion')},
            },
        ),
    ]
