# Generated by Django 6.0.3 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar_coltrade', '0002_accionpps_youtube_url_alter_accionpps_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionpps',
            name='areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='accionpps',
            name='destinatarios',
            field=models.CharField(choices=[('todos', 'Todos'), ('lideres', 'Lideres'), ('colaboradores', 'Colaboradores')], default='todos', max_length=20),
        ),
        migrations.AddField(
            model_name='accionpps',
            name='aplica_empresa',
            field=models.BooleanField(default=False),
        ),
    ]
