# Generated by Django 6.0.3 on 2026-04-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar_coltrade', '0003_accionpps_destinatarios_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionpps',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accionpps',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
