# Generated by Django 6.0.3 on 2026-04-08 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar_coltrade', '0004_accionpps_fecha_fin_accionpps_fecha_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamobeneficio',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_beneficios_pps', to=settings.AUTH_USER_MODEL),
        ),
    ]
