# Generated by Django 6.0.3 on 2026-04-08 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar_coltrade', '0005_reclamobeneficio_aprobado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accionpps',
            name='aprobador_todos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accionpps',
            name='aprobadores',
            field=models.ManyToManyField(blank=True, related_name='aprobador_acciones_permitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='aprobador_todos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='aprobadores',
            field=models.ManyToManyField(blank=True, related_name='aprobador_beneficios_permitidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
