# Generated by Django 6.0.3 on 2026-04-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar_coltrade', '0006_accionpps_aprobador_todos_accionpps_aprobadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
