# Generated by Django 6.0.3 on 2026-04-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienestar_coltrade', '0007_beneficio_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='niveles_permitidos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
