# Generated by Django 6.0.3 on 2026-03-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contacto_emergencia_email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contacto_emergencia_nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contacto_emergencia_parentesco',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contacto_emergencia_telefono',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
    ]
