# Generated by Django 6.0.3 on 2026-03-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_usuario_contacto_emergencia_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, choices=[('trade', 'Trade Marketing'), ('supli', 'Supply Chain'), ('people', 'People & Cultura'), ('comercial', 'Comercial'), ('logistica', 'Logistica'), ('tecnologia', 'Tecnologia'), ('finanzas', 'Finanzas'), ('administracion', 'Administracion'), ('otra', 'Otra')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('colaborador', 'Colaborador'), ('lider', 'Lider')], max_length=20, null=True),
        ),
    ]
