# Generated by Django 6.0.3 on 2026-04-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usuario_area_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('colaborador', 'Colaborador'), ('lider', 'Lider'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
