# Generated by Codex on 2026-04-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_usuario_tipo_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_codes",
                        to="user.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_codes",
                "indexes": [
                    models.Index(fields=["user", "code"], name="pwdreset_user_code_idx"),
                    models.Index(fields=["expires_at"], name="pwdreset_expires_idx"),
                ],
            },
        ),
    ]
