# Generated by Django 6.0.3 on 2026-04-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_password_reset_code'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='password_re_user_id_3e1601_idx',
            old_name='pwdreset_user_code_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='password_re_expires_8cf690_idx',
            old_name='pwdreset_expires_idx',
        ),
    ]
