# Generated by Django 6.0.3 on 2026-05-24 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_pwdreset_user_code_idx_password_re_user_id_3e1601_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_directos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, choices=[('trade', 'Trade Marketing'), ('supli', 'Supply Chain'), ('people', 'People & Cultura'), ('comercial', 'Comercial'), ('logistica', 'Logistica'), ('tecnologia', 'Tecnologia'), ('bi', 'BI'), ('ceo', 'CEO'), ('finanzas', 'Finanzas'), ('administracion', 'Administracion'), ('otra', 'Otra')], max_length=30, null=True),
        ),
    ]
