# Generated by Django 6.0.3 on 2026-05-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_usuario_cargo_usuario_jefe_directo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, choices=[('ceo', 'Presidencia'), ('direccion_comercial', 'Direccion Comercial'), ('tecnologia', 'Tech'), ('accounting', 'Accounting'), ('finanzas', 'Finance'), ('sales', 'Sales'), ('operations', 'Operations (Ops)'), ('procurement', 'Procurement'), ('trade', 'Trade Marketing'), ('brands', 'Brands'), ('bi', 'Business Intelligence'), ('sales_corporativo', 'Sales Corporativo'), ('sales_retail', 'Sales Retail'), ('people', 'People'), ('quality', 'Quality')], max_length=30, null=True),
        ),
    ]
