# Generated by Django 6.0.3 on 2026-03-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id_canal', models.AutoField(primary_key=True, serialize=False)),
                ('canal_nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canales',
                'db_table': 'canal',
            },
        ),
        migrations.CreateModel(
            name='ProductoAbastecimiento',
            fields=[
                ('id_producto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100)),
                ('id_canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='abastecimientos.canal')),
            ],
            options={
                'verbose_name': 'Producto de abastecimiento',
                'verbose_name_plural': 'Productos de abastecimiento',
                'db_table': 'productos_abastecimiento',
            },
        ),
        migrations.CreateModel(
            name='PuntoVentaAbastecimiento',
            fields=[
                ('id_puntoventa', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('punto_venta', models.CharField(max_length=255)),
                ('canal_regional', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=100)),
                ('id_canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puntos_venta', to='abastecimientos.canal')),
            ],
            options={
                'verbose_name': 'Punto de venta de abastecimiento',
                'verbose_name_plural': 'Puntos de venta de abastecimiento',
                'db_table': 'puntos_venta_abastecimiento',
            },
        ),
        migrations.CreateModel(
            name='MetaAbastecimiento',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_meta', models.PositiveIntegerField()),
                ('id_canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='abastecimientos.canal')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='abastecimientos.productoabastecimiento')),
                ('id_puntoventa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='abastecimientos.puntoventaabastecimiento')),
            ],
            options={
                'verbose_name': 'Meta de abastecimiento',
                'verbose_name_plural': 'Metas de abastecimiento',
                'db_table': 'meta_abastecimiento',
            },
        ),
        migrations.CreateModel(
            name='InventarioAbastecimiento',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_inventario', models.PositiveIntegerField()),
                ('id_canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='abastecimientos.canal')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='abastecimientos.productoabastecimiento')),
                ('id_puntoventa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='abastecimientos.puntoventaabastecimiento')),
            ],
            options={
                'verbose_name': 'Inventario de abastecimiento',
                'verbose_name_plural': 'Inventarios de abastecimiento',
                'db_table': 'inventario_abastecimiento',
            },
        ),
        migrations.CreateModel(
            name='TransitoAbastecimiento',
            fields=[
                ('id_transito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_transito', models.PositiveIntegerField()),
                ('id_canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitos', to='abastecimientos.canal')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitos', to='abastecimientos.productoabastecimiento')),
                ('id_puntoventa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitos', to='abastecimientos.puntoventaabastecimiento')),
            ],
            options={
                'verbose_name': 'Tránsito de abastecimiento',
                'verbose_name_plural': 'Tránsitos de abastecimiento',
                'db_table': 'transitos_abastecimiento',
            },
        ),
        migrations.CreateModel(
            name='VentaAbastecimiento',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_venta', models.PositiveIntegerField()),
                ('fecha_venta', models.DateField()),
                ('id_canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='abastecimientos.canal')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='abastecimientos.productoabastecimiento')),
                ('id_puntoventa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='abastecimientos.puntoventaabastecimiento')),
            ],
            options={
                'verbose_name': 'Venta de abastecimiento',
                'verbose_name_plural': 'Ventas de abastecimiento',
                'db_table': 'ventas_abastecimiento',
            },
        ),
    ]
