# Generated by Django 6.0.3 on 2026-03-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='id_canal',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
