# Generated by Django 6.0.3 on 2026-03-20 16:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimientos', '0002_alter_canal_id_canal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbastecimientoClaro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=255)),
                ('centro_costos', models.CharField(max_length=20)),
                ('nombre_punto', models.CharField(max_length=255)),
                ('inventario_claro', models.IntegerField(default=0)),
                ('transito_claro', models.IntegerField(default=0)),
                ('ventas_pasadas_claro', models.IntegerField(default=0)),
                ('ventas_actuales_claro', models.IntegerField(default=0)),
                ('sugerido_claro', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Abastecimiento Claro',
                'verbose_name_plural': 'Abastecimientos Claro',
                'db_table': 'abastecimiento_claro',
            },
        ),
        migrations.CreateModel(
            name='AbastecimientoColtrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('centro_costos', models.CharField(max_length=20)),
                ('punto_venta', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=20)),
                ('producto', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100)),
                ('ventas_actuales', models.IntegerField(default=0)),
                ('transitos', models.IntegerField(default=0)),
                ('inventario', models.IntegerField(default=0)),
                ('envio_inventario_3_meses', models.IntegerField(default=0)),
                ('sugerido_coltrade', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Abastecimiento Coltrade',
                'verbose_name_plural': 'Abastecimientos Coltrade',
                'db_table': 'abastecimiento_coltrade',
            },
        ),
    ]
