# Generated by Django 6.0.3 on 2026-05-24 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: A, B, C', max_length=10)),
                ('nombre', models.CharField(help_text='Ej: CULTURA, ESTRUCTURA OPERACIONAL', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'valoracion_competencias',
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='CicloEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('lider', 'Evaluacion de Liderazgo'), ('operativo', 'Evaluacion Operativa/Tactica'), ('mixta', 'Mixta')], default='mixta', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('activo', 'Activo'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='programado', max_length=20)),
                ('anonimato', models.BooleanField(default=False, help_text='Si esta activo, el evaluador no se muestra al evaluado')),
                ('comentarios_obligatorios', models.BooleanField(default=False)),
                ('peso_jefe_lider', models.PositiveSmallIntegerField(default=60, help_text='Peso % del jefe en evaluacion de lider (default 60)')),
                ('peso_equipo_lider', models.PositiveSmallIntegerField(default=40, help_text='Peso % del equipo en evaluacion de lider (default 40)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'valoracion_ciclos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_evaluador', models.CharField(choices=[('jefe', 'Jefe Inmediato'), ('equipo', 'Miembro del Equipo'), ('autoevaluacion', 'Autoevaluacion')], max_length=20)),
                ('tipo_evaluacion', models.CharField(choices=[('lider', 'Evaluacion de Liderazgo'), ('operativo', 'Evaluacion Operativa/Tactica')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('observaciones_acuerdos', models.TextField(blank=True, help_text='Campo libre de observaciones y acuerdos (no califica)')),
                ('fecha_inicio_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_a_realizar', to=settings.AUTH_USER_MODEL)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='modulo_valoracion.cicloevaluacion')),
            ],
            options={
                'db_table': 'valoracion_asignaciones',
                'ordering': ['ciclo', 'evaluado'],
                'unique_together': {('ciclo', 'evaluador', 'evaluado')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo_evaluacion', models.CharField(choices=[('lider', 'Evaluacion de Liderazgo'), ('operativo', 'Evaluacion Operativa/Tactica')], max_length=20)),
                ('tipo_pregunta', models.CharField(choices=[('likert', 'Escala 1-5'), ('abierta', 'Pregunta Abierta')], default='likert', max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, help_text='Peso relativo dentro de la competencia', max_digits=5)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('obligatoria', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='modulo_valoracion.competencia')),
            ],
            options={
                'db_table': 'valoracion_preguntas',
                'ordering': ['competencia__orden', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evaluacion', models.CharField(choices=[('lider', 'Evaluacion de Liderazgo'), ('operativo', 'Evaluacion Operativa/Tactica')], max_length=20)),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('semaforo', models.CharField(choices=[('referente', 'Es un referente'), ('consolidado', 'Esta consolidado'), ('desarrollo', 'En desarrollo'), ('acompanamiento', 'Requiere acompanamiento'), ('intervencion', 'Requiere intervencion inmediata')], default='intervencion', max_length=20)),
                ('puntaje_jefe', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('puntaje_equipo', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fortalezas', models.JSONField(blank=True, default=list)),
                ('brechas', models.JSONField(blank=True, default=list)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='modulo_valoracion.cicloevaluacion')),
                ('evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_valoracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'valoracion_resultados',
                'ordering': ['-porcentaje'],
                'unique_together': {('ciclo', 'evaluado')},
            },
        ),
        migrations.CreateModel(
            name='PlanAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_compromiso', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('cumplido', 'Cumplido'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('evidencia_url', models.URLField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_accion_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_accion_asignados', to=settings.AUTH_USER_MODEL)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_accion', to='modulo_valoracion.resultadoevaluacion')),
            ],
            options={
                'db_table': 'valoracion_planes_accion',
                'ordering': ['estado', 'fecha_compromiso'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveSmallIntegerField(blank=True, help_text='Valor 1-5 para preguntas tipo likert', null=True)),
                ('respuesta_abierta', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='modulo_valoracion.asignacionevaluacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='modulo_valoracion.pregunta')),
            ],
            options={
                'db_table': 'valoracion_respuestas',
                'unique_together': {('asignacion', 'pregunta')},
            },
        ),
    ]
