# Generated by Django 6.0.3 on 2026-06-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_valoracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloevaluacion',
            name='preguntas_excluidas',
            field=models.JSONField(blank=True, default=list, help_text='IDs de preguntas que NO se aplican en este ciclo'),
        ),
    ]
