# Generated by Django 6.0.3 on 2026-06-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_valoracion', '0002_cicloevaluacion_preguntas_excluidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='activa',
            field=models.BooleanField(default=True, help_text='Si esta desactivada, no aplica para responder ni consolidar'),
        ),
    ]
