# Generated by Django 6.0.3 on 2026-08-24 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_valoracion', '0004_resultado_consolidado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionValoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultados_publicados', models.BooleanField(default=False, help_text='Si esta activo, el equipo puede ver Mis Resultados y Planes de Accion')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_valoracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracion del modulo',
                'verbose_name_plural': 'Configuracion del modulo',
                'db_table': 'valoracion_configuracion',
            },
        ),
    ]
